# Generated by Django 5.2.4 on 2025-08-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan/Coupe (2 Seats)'), ('suv5', 'SUV (5 Seats)'), ('suv7', 'Pick Up/7-Seat SUV'), ('xlsuv', 'XL SUV')], max_length=10)),
                ('service_type', models.CharField(choices=[('full', 'Full Detail'), ('interior', 'Interior Detail'), ('exterior', 'Exterior Detail')], max_length=10)),
                ('package_type', models.CharField(choices=[('bronze', 'Bronze'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
