# Generated by Django 5.2.4 on 2025-08-26 12:45

import uuid
from django.db import migrations, models

def generate_unique_slugs(apps, schema_editor):
    Booking = apps.get_model('app', 'Booking')
    for booking in Booking.objects.all():
        booking.slug = str(uuid.uuid4())
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=False), # Initially allow null and not unique
        ),
        migrations.RunPython(
            code=generate_unique_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, null=False),
        ),
    ]
